version: '3.9'
services:
  database:
    image: postgres
    container_name: nestg-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-gaming
    volumes:
      - pgdata:/var/lib/postgresql/data
  nestgaming:
    container_name: nestg-api
    image: nest-gaming
    build: .
    depends_on:
      - database
    ports:
      - 3000:3000
volumes:
  pgdata:
